version: "3"
services:
  ecom-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ecom-backend
    command: npm start --reload
    ports:
      - "3000:3000"
    volumes:
      - "./:/app:delegated"
      - "/app/node_modules"
    restart: unless-stopped
    env_file:
      - .env
